engines:
  pep8:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - python

ratings:
  paths:
    - "**.py"
    - "**.js"
    - "**.css"

exclude_paths:
  - lib/**/*
  - static/css/bootstrap*
  - static/css/font*
  - static/fonts/*
  - static/image/*
  - static/js/bootstrap*
  - static/js/npm.js
