language: python
python: 2.7
install:
  - pip install -t lib -r requirements.txt
  - pip install mock
  - pip install coverage
script: coverage run -m unittest discover tests
after_success: coverage report
before_deploy:
  - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in appengine_keyfile.json.enc -out appengine_keyfile.json -d
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: appengine_keyfile.json
  project: gioca-estate
  on: master