language: python
python: 2.7
install:
  - pip install -t lib -r requirements.txt
  - pip install mock
  - pip install coverage
  - pip install python-coveralls
before_script: 
  - npm install
  - gulp
script:
  - coverage run --omit="tests/*","*/__init__.py","*/mock.py" -m unittest discover tests
after_success:
  - coverage report
  - coveralls
before_deploy:
  - rm -rf node_modules
  - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in appengine_keyfile.json.enc -out appengine_keyfile.json -d
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: appengine_keyfile.json
  project: gioca-estate
  on: master

