language: python
python: 2.7
install: pip install -t lib -r requirements.txt
script: python -m unittest discover tests
before_install:
- openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv
  -in appengine_keyfile.json.enc -out appengine_keyfile.json -d
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: appengine_keyfile.json
  project: gioca-estate
  on: master